### ISSUE TITLE
 File "main1.751.py", line 1192, in main

### ISSUE THREAD

**Issue by vietnga20081** [jackjayyu/TG-Tools#8]
Choose an Option: 4
[+] Accounts getting ready...

[+] Total Accounts: 0
Traceback (most recent call last):
  File "main1.751.py", line 1441, in <module>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "main1.751.py", line 1192, in main
IndexError: list index out of range

**Comment by jackjayyu** [comment]
Make sure to login with accounts first.
